project:
  type: book

book:
  title: "Modelos ResNET para determinar la progresi√≥n de la Dementia"
  author: "Daniella Guerra & Tawny Torres"
  date: "17/11/2025"
  chapters:
    - index.qmd
    - 1_ETL_IMAGES.ipynb
    - 2_EDA.ipynb

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    code-fold: true
  pdf:
    documentclass: scrreprt
    code-blocks: false

